version: '3.9'
services:
  mysql_fa:
    image: mysql:latest
    restart: always
    container_name: mysql_fa
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freedom_average
      MYSQL_USER: freedom
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - mysql:/var/lib/mysql

  freedom-average:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freedom-average
    volumes:
      - .:/app
    ports:
      - 3001:3001
    # expose:
    #   - 3001

volumes:
  mysql:

networks:
  default:
    external:
      name: titan-chest-network
